### ISSUE TITLE
Duplicates are not found when in the same file

### ISSUE THREAD

**Issue by cdelmas** [kucherenko/jscpd#189]
**Describe the bug**
No duplicates are found when they are in the same file.
(At least with javascript, not tried for another format).

**To Reproduce**
Have one file, introduce a duplicate inside -> no duplicate found
Copy or move one duplicate block into another file -> duplicate found

**Expected behavior**
The duplicate should be found, even when they are in the same file. It was the case in 0.6 (I found this behavior when upgrading).

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - OS Version 18.04.1
 - NodeJS 10.14.1

**Comment by kucherenko** [comment]
Thank you for the report, will fix it

**Comment by kucherenko** [comment]
Fixed in jscpd@2.0.3

**Comment by jjb** [comment]
I'm still having this problem in 2.0.16

`jscpd --min-tokens 2 --mode weak myfile.txt` comes up with no results when I know there should be

let me know if you want more info

**Comment by jjb** [comment]
Nevermind- my file was too big. increasing max-lines and max-size did the trick. sorry for the noise!
